### ISSUE TITLE
to do list 

### ISSUE THREAD

**Issue by Tichoo07** [zuri-training/auth-wiki-team7#111]
Style guides
-Colors
-Icons 
User research 
Brainstorming
Sign up page
Login page
Search overlay
Notification overlay
Worked on prototype
Worked on the matrix
Empathy map
Prototype 
High fidelity
Forgot password page
Reset password page
Create new password
Page
Error page
Code sample page

**Comment by bendgrapher** [comment]
Style guides
-Colors
-Icons
User research (please add google doc link)
Brainstorming -
https://www.figma.com/file/8gUAln2Adg3QiUvbki4CyM/Team-7_Authwiki?node-id=34%3A333
Sign up page-
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=251%3A10818
Login page -
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=1026%3A5006
Search overlay-
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=1077%3A2991
Notification overlay -
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=1026%3A6526
Worked on prototype
Worked on the matrix -
https://www.figma.com/file/8gUAln2Adg3QiUvbki4CyM/Team-7_Authwiki?node-id=34%3A67
Empathy map(link to the entire empathy map) -
https://www.figma.com/file/8gUAln2Adg3QiUvbki4CyM/Team-7_Authwiki?node-id=50%3A313
Prototype
High fidelity
Forgot password page -
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=1571%3A2789
Reset password page-
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=2002%3A2658
Create new password -
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=2002%3A2762
Page
Error page -
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=1026%3A5325
Code sample page (HI-FI) -
https://www.figma.com/file/kDCI1y7yvPq16hHCpObLj5/Team-7_Authwiki?node-id=2174%3A3253
